---
genPolicy: "None"
openAPISpec: "http://localhost:8090/v2/api-docs"
generators:
- type: "no_params"
  assertions:
  - "@StatusCode == 200"
  tags: null
  severity: "Major"
  database: null
  inactive: true
  matches: []
  authors: ""
- type: "sla"
  assertions:
  - "@StatusCode == 200 AND @ResponseTime < 500"
  tags: null
  severity: "Major"
  database: null
  inactive: true
  matches:
  - name: null
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: null
    resourceSamples: null
    queryParams: null
    bodyProperties: null
  authors: ""
- type: "anonymous_invalid"
  assertions:
  - "@StatusCode == 401 OR @StatusCode == 403"
  tags: null
  severity: "Major"
  database: null
  inactive: true
  matches:
  - name: null
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: ""
    resourceSamples: null
    queryParams: null
    bodyProperties: null
  authors: ""
- type: "auth_invalid"
  assertions:
  - "@StatusCode == 401 OR @StatusCode == 403"
  tags: null
  severity: "Major"
  database: null
  inactive: true
  matches:
  - name: null
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: ""
    resourceSamples: null
    queryParams: null
    bodyProperties: null
  authors: ""
- type: "auth_invalid_empty"
  assertions:
  - "@StatusCode == 401 OR @StatusCode == 403"
  tags: null
  severity: "Major"
  database: null
  inactive: true
  matches:
  - name: null
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: ""
    resourceSamples: null
    queryParams: null
    bodyProperties: null
  authors: ""
- type: "auth_invalid_sql"
  assertions:
  - "@StatusCode == 401 OR @StatusCode == 403"
  tags: null
  severity: "Major"
  database: null
  inactive: true
  matches:
  - name: null
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: ""
    resourceSamples: null
    queryParams: null
    bodyProperties: null
  authors: ""
- type: "rbac"
  assertions:
  - "Disallowed:@StatusCode == 401 OR @StatusCode == 403"
  - "Allowed:@StatusCode != 401 AND @StatusCode != 403"
  tags: null
  severity: "Major"
  database: null
  inactive: false
  matches:
  - name: "ROLE_ADMIN,ROLE_PM,ROLE_USER"
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: null
    resourceSamples: "GET:/api/v1/accounts:Allowed[ROLE_ADMIN,ROLE_PM]\nPOST:/api/v1/accounts:Allowed[ROLE_ADMIN,ROLE_PM]\n\
      DELETE:/api/v1/accounts/{id}:Allowed[ROLE_ADMIN,ROLE_PM]\nGET:/api/v1/accounts/{id}:Allowed[ROLE_ADMIN,ROLE_PM]\n\
      PUT:/api/v1/accounts/{id}:Allowed[ROLE_ADMIN,ROLE_PM]\nGET:/api/v1/accounts/account-type/{accountType}:Allowed[ROLE_ADMIN,ROLE_PM]\n\
      POST:/api/v1/accounts/batch:Allowed[ROLE_ADMIN,ROLE_PM]\nGET:/api/v1/alerts/{id}:Allowed[ROLE_ADMIN]\n\
      PUT:/api/v1/bot-clusters/{id}:Allowed[ROLE_ADMIN]\nDELETE:/api/v1/bot-clusters/{id}:Allowed[ROLE_ADMIN]\n\
      GET:/api/v1/bot-clusters/{id}/ping:Allowed[ROLE_ADMIN]\nPUT:/api/v1/bot-clusters/{id}/terminal:Allowed[ROLE_ADMIN]\n\
      GET:/api/v1/dashboard/count-tests-between:Allowed[ROLE_ADMIN]\nGET:/api/v1/dashboard/count-time:Allowed[ROLE_ADMIN]\n\
      GET:/api/v1/dashboard/count-time-between:Allowed[ROLE_ADMIN]\nPUT:/api/v1/envs:Allowed[ROLE_ADMIN]\n\
      POST:/api/v1/data-sets/batch:Allowed[ROLE_ADMIN]\nPOST:/api/v1/envs:Allowed[ROLE_ADMIN]\n\
      DELETE:/api/v1/envs/{id}:Allowed[ROLE_ADMIN]\nPOST:/api/v1/envs/batch:Allowed[ROLE_ADMIN]\n"
    queryParams: null
    bodyProperties: null
  authors: "jaleel"
- type: "abac"
  assertions:
  - "Create:@StatusCode == 200 OR @StatusCode == 201"
  - "Disallowed:@StatusCode == 401 OR @StatusCode == 403"
  tags: null
  severity: "Major"
  database: null
  inactive: true
  matches: []
  authors: ""
- type: "DDOS"
  assertions:
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  tags: null
  severity: "Major"
  database: null
  inactive: true
  matches:
  - name: "pageSize, page_size, maxResults, max_results"
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: null
    resourceSamples: null
    queryParams: null
    bodyProperties: null
  authors: ""
- type: "XSS_Injection"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  tags: null
  severity: "Major"
  database: null
  inactive: true
  matches: []
  authors: ""
- type: "sql_injection_timebound"
  assertions:
  - "@ResponseTime < 7000 OR @ResponseTime > 10000"
  - "@StatusCode != 404"
  tags: null
  severity: "Major"
  database:
    name: "MySQL"
    version: "5.7"
  inactive: true
  matches: []
  authors: ""
- type: "log_Forging"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  tags: null
  severity: "Major"
  database: null
  inactive: true
  matches: []
  authors: ""
- type: "invalid_datatype"
  assertions:
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  tags: null
  severity: "Major"
  database: null
  inactive: true
  matches: []
  authors: ""
- type: "special_chars "
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  tags: null
  severity: "Major"
  database: null
  inactive: true
  matches: []
  authors: ""
- type: "null_value"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  tags: null
  severity: "Major"
  database: null
  inactive: true
  matches: []
  authors: ""
- type: "empty_value"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  tags: null
  severity: "Major"
  database: null
  inactive: true
  matches: []
  authors: ""
- type: "negative_number"
  assertions:
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  tags: null
  severity: "Major"
  database: null
  inactive: true
  matches: []
  authors: ""
- type: "customize"
  assertions: []
  tags: null
  severity: null
  database: null
  inactive: false
  matches:
  - name: null
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: null
    resourceSamples: "Get:/api/v1/alerts[Accept=application/json,Content-Type=application/json]\n\
      Post:/api/v1/accounts[Accept: application/json,Content-Type: application/json]"
    queryParams: null
    bodyProperties: null
  authors: ""
