---
parent: "api_v1_projects_projectid_new_autocodeconfig"
name: "ApiV1ProjectsProjectidNewAutocodeconfigPostRoleAdminDisallowedRbac"
description: null
authors:
- "FX Bot"
- "jaleel"
type: "SUITE"
init: []
path: "/api/v1/projects/{projectId}/new/autocodeconfig"
endpoint: "/api/v1/projects/{{@Random}}/new/autocodeconfig"
method: "POST"
auth: "ROLE_ADMIN"
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases:
- id: 1
  body: "{\r\n  'createdBy' : null,\r\n  'createdDate' : null,\r\n  'genPolicy' :\
    \ 'Create',\r\n  'generators' : [ ],\r\n  'id' : null,\r\n  'inactive' : null,\r\
    \n  'modifiedBy' : null,\r\n  'modifiedDate' : null,\r\n  'openAPISpec' : null,\r\
    \n  'project' : {\r\n    'account' : {\r\n      'accountType' : 'Local',\r\n \
    \     'createdBy' : null,\r\n      'createdDate' : null,\r\n      'id' : null,\r\
    \n      'inactive' : null,\r\n      'modifiedBy' : null,\r\n      'modifiedDate'\
    \ : null,\r\n      'name' : null,\r\n      'org' : {\r\n        'createdBy' :\
    \ null,\r\n        'createdDate' : null,\r\n        'id' : null,\r\n        'inactive'\
    \ : null,\r\n        'modifiedBy' : null,\r\n        'modifiedDate' : null,\r\n\
    \        'name' : null,\r\n        'version' : null\r\n      },\r\n      'region'\
    \ : null,\r\n      'version' : null\r\n    },\r\n    'autoGenSuites' : null,\r\
    \n    'branch' : null,\r\n    'createdBy' : null,\r\n    'createdDate' : null,\r\
    \n    'description' : null,\r\n    'genPolicy' : 'None',\r\n    'id' : null,\r\
    \n    'inactive' : null,\r\n    'lastCommit' : null,\r\n    'lastSync' : null,\r\
    \n    'licenses' : [ ],\r\n    'modifiedBy' : null,\r\n    'modifiedDate' : null,\r\
    \n    'name' : null,\r\n    'openAPISpec' : null,\r\n    'org' : {\r\n      'createdBy'\
    \ : null,\r\n      'createdDate' : null,\r\n      'id' : null,\r\n      'inactive'\
    \ : null,\r\n      'modifiedBy' : null,\r\n      'modifiedDate' : null,\r\n  \
    \    'name' : null,\r\n      'version' : null\r\n    },\r\n    'props' : null,\r\
    \n    'url' : null,\r\n    'version' : null\r\n  },\r\n  'version' : null\r\n}"
  inactive: false
assertions:
- "@StatusCode == 401 OR @StatusCode == 403"
cleanup: []
severity: "Major"
category: "RBAC"
tags:
- "V1"
- "OWASP - OTG-IDENT-001 "
- "FX Top 10 - API Vulnerability"
inactive: false
policies: null
autoGenerated: true
